---
- name: Check directory exists
  register: clt_directory
  stat:
    path: /Library/Developer/CommandLineTools
  tags:
    - clt

- name: Check pkgutil info
  check_mode: False
  ignore_errors: True
  changed_when: False
  failed_when: False
  register: clt_pkgutil
  command: pkgutil --pkg-info=com.apple.pkg.CLTools_Executables
  tags:
    - clt

- name: Touch ondemand file
  when: clt_pkgutil.rc != 0 or not clt_directory.stat.exists
  file:
    path: /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
    state: touch
  tags:
    - clt

- name: Parse softwareupdate old
  changed_when: False
  failed_when: clt_updates_old.rc != 0 or clt_updates_old.stdout | length == 0
  register: clt_updates_old
  when:
    - clt_pkgutil.rc != 0 or not clt_directory.stat.exists
    - ansible_distribution_version is version("10.15", "<")
  shell: |
    softwareupdate -l | grep -B 1 -E 'Command Line Tools' | awk -F'*' '/^ +\*/ {print $2}' | sed 's/^ *//' | grep -iE '[0-9|.]' | sort | tail -n1
  tags:
    - clt

- name: Update detection old
  set_fact:
    clt_updates: "{{ clt_updates_old }}"
  when: clt_updates_old is not skipped
  tags:
    - clt

- name: Parse softwareupdate new
  changed_when: False
  failed_when: clt_updates_new.rc != 0 or clt_updates_new.stdout | length == 0
  register: clt_updates_new
  when:
    - clt_pkgutil.rc != 0 or not clt_directory.stat.exists
    - ansible_distribution_version is version("10.15", ">=")
  shell: |
    softwareupdate -l | grep -B 1 -E 'Command Line Tools' | awk -F'*' '/^\*/ {print $2}' | sed 's/^ Label: //' | grep -iE '[0-9|.]' | sort | tail -n1
  tags:
    - clt

- name: Update detection new
  set_fact:
    clt_updates: "{{ clt_updates_new }}"
  when: clt_updates_new is not skipped
  tags:
    - clt

- name: Install required package
  notify:
    - Cleanup clt
  failed_when: clt_install.rc != 0 or "Error installing updates." in clt_install.stdout
  register: clt_install
  when: clt_pkgutil.rc != 0 or not clt_directory.stat.exists
  command: softwareupdate -i "{{ clt_updates.stdout }}"
  tags:
    - clt

...
